version: "3.8"

services:
# Infra services
  cassandra-node-0:
    image: cassandra
    container_name: cassandra-node-0
    environment:
      - CASSANDRA_SEEDS=cassandra-node-0,cassandra-node-1,cassandra-node-2
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=dc1
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
    ports:
      - "7000:7000"   # 노드간 클러스터 내부 통신
      - "7001:7001"   # 노드간 보안 통신에 사용
      - "9042:9042"   # CQL 클라이언트와 통신
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 10s
      timeout: 10s
      retries: 50
    networks:
      black-net:
        ipv4_address: 172.18.0.2

  cassandra-node-1:
    image: cassandra
    container_name: cassandra-node-1
    environment:
      - CASSANDRA_SEEDS=cassandra-node-0,cassandra-node-1,cassandra-node-2
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=dc1
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
    ports:
      - "17000:7000"
      - "17001:7001"
      - "19042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 10s
      timeout: 10s
      retries: 50
    networks:
      black-net:
        ipv4_address: 172.18.0.3

  cassandra-node-2:
    image: cassandra
    container_name: cassandra-node-2
    environment:
      - CASSANDRA_SEEDS=cassandra-node-0,cassandra-node-1,cassandra-node-2
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=dc1
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
    ports:
      - "27000:7000"
      - "27001:7001"
      - "29042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 10s
      timeout: 10s
      retries: 50
    networks:
      black-net:
        ipv4_address: 172.18.0.4

  db:
    image: "mariadb:latest"
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: eddy
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - redis
    networks:
      black-net:
        ipv4_address: 172.18.0.5

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      black-net:
        ipv4_address: 172.18.0.6

# Domain Services
  massive-member:
    image: massive-member
    container_name: massive-member
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      black-net:
        ipv4_address: 172.18.0.7

  massive-order:
    image: massive-order
    container_name: massive-order
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      black-net:
        ipv4_address: 172.18.0.8

  massive-delivery:
    image: massive-delivery
    container_name: massive-delivery
    ports:
      - "8083:8083"
    depends_on:
      - db
    networks:
      black-net:
        ipv4_address: 172.18.0.9

  massive-catalog:
    image: massive-catalog
    container_name: massive-catalog
    ports:
      - "8084:8084"
    depends_on:
      - db
    networks:
      black-net:
        ipv4_address: 172.18.0.10

  massive-search:
    image: massive-search
    container_name: massive-search
    ports:
      - "8085:8085"
    depends_on:
      - db
    networks:
      black-net:
        ipv4_address: 172.18.0.11

  massive-payment:
    image: massive-payment
    container_name: massive-payment
    ports:
      - "8086:8086"
    depends_on:
      - db
    networks:
      black-net:
        ipv4_address: 172.18.0.12

networks:
  black-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16