spring:
  application:
    name: massive-traffic-architecture
  cassandra:
    keyspace-name: my
    port: 9042
    contact-points: 127.0.0.1
    local-datacenter: datacenter11
    schema-action: create_if_not_exists