spring:
  application:
    name: massive-traffic-architecture
  cassandra:
    keyspace-name: my
    port: 9042
    contact-points: localhost
    local-datacenter: datacenter11
    schema-action: create_if_not_exists